### PR TITLE
Added Info-Tech Research Group to list of companies using Rails

### PR DESCRIPTION
**Pull request by jamiestrachan**

### CODE REVIEW

**Comment by jamiestrachan** [comment]
Sorry, I didn't mean to bundle these two changes. I can pull them apart if you'd prefer.

**Comment by pauldowman** [comment]
No problem for the bundled commit. But does ITRG provide Rails education specifically?

**Comment by jamiestrachan** [comment]
Maybe I misunderstood, but I listed us under "Other Companies Using Rails" because we use Rails for development. Is that not what that section is for?

**Comment by pauldowman** [comment]
Sorry @jamiestrachan I misread the diff, I thought it was added under "education"! My fault. Will merge!

**Comment by jamiestrachan** [comment]
No problem. Thanks!

**Pull request merged**
