### PR TITLE
Update toronto ruby slack link to point to canonical one

### PR DESCRIPTION
**Pull request by Nitrodist**
The Toronto Ruby Brigade slack group and Jasdeep Singh's slack group are
combining the slack groups, so this link should point to the canonical
one now.

### CODE REVIEW

**Comment by pauldowman** [comment]
@jasdeepsingh can you confirm?

**Comment by pauldowman** [comment]
I'm going to close for now, re-open when we can get confirmation from @jasdeepsingh

**Comment by jasdeepsingh** [comment]
My apologies on being a little late on this. Yes, let's please proceed with this change.

**Comment by jasdeepsingh** [comment]
@Nitrodist how do we move all users from rubytoronto.slack.com to the proposed slack channel?

**Pull request merged**
